config/routes.rb
Togather::Application.routes.draw do

  #devise_for :users, skip: [:cancel]

  devise_for :users, skip: :registrations
  devise_scope :user do # will disable cancelling the account
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root to: 'welcome#index'

  get '/user', to: 'users#profile', as: 'profile'
  get '/profile/:id', to: 'users#profile', as: 'user'
  get '/profile', to: 'users#profile', as: 'user_root'

  resources :groups, except: [:index] do
    resources :comments, only: [:create]
    resources :events, except: [:index]
  end
  post '/groups/register/:id', to: 'groups#register', as: 'register'
  post '/groups/unregister/:id', to: 'groups#unregister', as: 'unregister'

  post '/groups/:group_id/events/:id/register', to: 'events#register', as: 'event_register'
  post '/groups/:group_id/events/:id/unregister', to: 'events#unregister', as: 'event_unregister'

  get '/search', to: 'groups#search', as: 'search'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :title, :message, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_group

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.group = @group
    if @comment.save
      redirect_to @group, notice: 'Comment was added successfully'
    else
      render template: 'groups/show'
    end
  end

  private

  def load_group
    @group = Group.find(params[:group_id])
  end

  def comment_params
    params.require(:comment).permit(:title, :message)
  end
end

app/views/comments/_form.html.erb
<div class="container">
  <%= form_for(@comment, url: group_comments_path(@group), html: {class: 'form-horizontal'}) do |f| %>
      <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group row">
        <%= f.label :title, class: 'col-sm-1 control-label' %>
        <div class="col-md-4">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :message, class: 'col-sm-1 control-label' %>
        <div class="col-md-4">
          <%= f.text_area :message, rows: 4, class: 'form-control' %>
        </div>
      </div>
      <div>
        <div class="col-md-offset-1 col-md-4">
          <%= f.submit class: 'btn btn-default' %>
        </div>
      </div>
  <% end %>
</div>