config/routes.rb
Togather::Application.routes.draw do

  #devise_for :users, skip: [:cancel]

  devise_for :users, skip: :registrations
  devise_scope :user do # will disable cancelling the account
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root to: 'welcome#index'

  get '/user', to: 'users#profile', as: 'profile'
  get '/profile/:id', to: 'users#profile', as: 'user'
  get '/profile', to: 'users#profile', as: 'user_root'

  resources :groups, except: [:index] do
    resources :comments, only: [:create]
    resources :events, except: [:index]
  end
  post '/groups/register/:id', to: 'groups#register', as: 'register'
  post '/groups/unregister/:id', to: 'groups#unregister', as: 'unregister'

  post '/groups/:group_id/events/:id/register', to: 'events#register', as: 'event_register'
  post '/groups/:group_id/events/:id/unregister', to: 'events#unregister', as: 'event_unregister'

  get '/search', to: 'groups#search', as: 'search'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships, source: :user
  has_many :comments, dependent: :delete_all
  has_many :events, dependent: :delete_all

  validates :name, presence: true
  validates :motto, presence: true

  enum category: [:culture, :business, :sport, :social, :family, :religion, :food, :technology, :hobbies, :pets]

  def add_user(user)
    users << user
  end

  def remove_user(user)
    users.delete(user)
  end

  def admin=(user)
    add_user user
    membership = memberships.find_by user: user
    membership.admin= true
    membership.save
  end

  def admin
    membership = memberships.where("admin = ?", true).first
    membership.user if membership.present?
  end

  def is_admin?(user)
    return false if user.blank?
    user == admin
  end

  def is_member?(user)
    return false if user.blank?
    memberships.find_by(user: user).present?
  end

  def current_events
    events.where("events.end > ?", Time.now)
  end

  def past_events
    events.where("events.end < ?", Time.now)
  end

  def self.search(query)
    if query
      query= "%#{query}%"
      Group.where('groups.name LIKE ? OR groups.motto LIKE ?', query, query)
    else
      nil
    end
  end

  def members_count
    self.memberships.count
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group_for_user, only: [:show, :register, :unregister]
  before_action :set_group_for_admin, only: [:edit, :update, :destroy]
  before_action :reference_data, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!

  def show
    @comment = Comment.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.admin= current_user
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to profile_url, notice: "You have deleted the group #{@group.name}."
  end

  def register
    if @group.add_user current_user
      redirect_to group_path, notice: "Yay! You are a member of #{@group.name} now."
    else
      redirect_to group_path, alert: "Error occurred. You are already a member of #{@group.name}!"
    end
  end

  def unregister
    @group.remove_user current_user
    redirect_to group_path, notice: "You've just left #{@group.name}"
  end

  def search
    @groups = Group.search(params[:q])
  end

  private

  def set_group_for_user
    @group = find_group_by_id
  end

  def set_group_for_admin
    set_group_for_user if find_group_by_id.is_admin? current_user
  end

  def group_params
    params.require(:group).permit(:name, :motto, :category)
  end

  def find_group_by_id
    Group.find(params[:id])
  end

  def reference_data
    @categories = Group.categories
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container">
  <%= form_for(@group, html: {class: 'form-horizontal'}) do |f| %>
      <% if @group.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

            <ul>
              <% @group.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group row">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-md-4">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :motto, class: 'col-sm-2 control-label' %>
        <div class="col-md-4">
          <%= f.text_area :motto, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :category, class: 'col-sm-2 control-label' %>
        <div class="col-md-4">
          <%= f.select :category, options_for_select(@categories.collect { |c| [c[0].humanize, c[0]] }, selected: f.object.category), {}, {class: 'form-control'} %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
          <%= f.submit class: 'btn btn-default' %>
        </div>
      </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

app/views/groups/search.html.erb
<div class="container">
  <h1>Search results:</h1>
  <% if @groups.present? %>
      <% @groups.each do |g| %>
          <h3><%= link_to g.name, g %></h3>
          <p><%= g.motto %></p>
      <% end %>
  <% else %>
      <p>We couldn't find any group based on your query but try out some of our other groups below!</p>
      <% Group.last(10).each do |g| %>
          <h3><%= link_to g.name, g %></h3>
          <p><%= g.motto %></p>
      <% end %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="col-md-12">
    <h1>
      Group <strong><%= @group.name %></strong> <span class="label label-primary"><%= @group.category.humanize %></span>
    </h1>

    <p><%= @group.motto %></p>
  </div>

  <div class="col-md-3 left-menu">
    <h2>Settings</h2>

    <% if @group.is_admin? current_user %>
        <p><%= link_to 'Edit group settings', edit_group_path(id: @group) %></p>

        <p><%= link_to 'Create event', new_group_event_path(group_id: @group) %></p>
    <% end %>
    <% if !@group.is_member? current_user %>
        <p><%= link_to 'Add me to the group!', register_path, method: :post %></p>
    <% elsif !@group.is_admin? current_user %>
        <p><%= link_to 'Leave group', unregister_path(@group), method: :post %></p>
    <% else %>
        <p><%= link_to 'Delete the group', @group, method: :delete, data: {confirm: 'Careful! You will delete the entire group!'} %></p>
    <% end %>

    <h2>Members</h2>

    <p>
      <% if @group.is_member? current_user %>
        <ul>
          <% @group.users.each do |user| %>
              <li><%= link_to user.name, user %></li>
          <% end %>
        </ul>
    <% else %>
        Only members can see other members in this group.
        <%= link_to 'Become a member!', register_path, method: :post %>
    <% end %>
    </p>

    <h2>Events</h2>
    <% if @group.is_member? current_user %>
        <h3>Upcoming</h3>
        <% if @group.current_events.present? %>
            <ul>
              <% @group.current_events.each do |e| %>
                  <li><%= link_to e.title, group_event_path(group_id: @group, id: e) %></li>
              <% end %>
            </ul>
        <% else %>
            There are no upcoming events.
        <% end %>
        <h3>Past</h3>
        <% if @group.past_events.present? %>
            <ul>
              <% @group.past_events.each do |e| %>
                  <li><%= link_to e.title, group_event_path(group_id: @group, id: e) %></li>
              <% end %>
            </ul>
        <% else %>
            There are no past events.
        <% end %>
    <% else %>
        <p>Only members can see events of this group.</p>
    <% end %>

  </div>

  <div class="col-md-6">
    <h2>Board</h2>
    <% if @group.is_member? current_user %>
        <%= render file: 'comments/_form' %>
        <hr/>
        <% @group.comments.each do |c| %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <%= c.title %>
                <span class="pull-right">, <%= c.created_at.to_s(:long) %> </span>
                <span class="pull-right">by <%= link_to c.user.name, c.user %></span>
              </div>
              <div class="panel-body">
                <p><%= c.message %></p>
              </div>
            </div>
        <% end %>
    <% else %>
        <p>Discussion only for members.</p>
    <% end %>
  </div>
</div>