config/routes.rb
Togather::Application.routes.draw do

  #devise_for :users, skip: [:cancel]

  devise_for :users, skip: :registrations
  devise_scope :user do # will disable cancelling the account
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root to: 'welcome#index'

  get '/user', to: 'users#profile', as: 'profile'
  get '/profile/:id', to: 'users#profile', as: 'user'
  get '/profile', to: 'users#profile', as: 'user_root'

  resources :groups, except: [:index] do
    resources :comments, only: [:create]
    resources :events, except: [:index]
  end
  post '/groups/register/:id', to: 'groups#register', as: 'register'
  post '/groups/unregister/:id', to: 'groups#unregister', as: 'unregister'

  post '/groups/:group_id/events/:id/register', to: 'events#register', as: 'event_register'
  post '/groups/:group_id/events/:id/unregister', to: 'events#unregister', as: 'event_unregister'

  get '/search', to: 'groups#search', as: 'search'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :group
  has_and_belongs_to_many :users

  validates :title, :description, :beginning, :end, presence: true

  def is_user_attending? user
    users.where("users.id = ?", user).present?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :load_group
  before_action :add_event, except: [:new, :create]

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    adjust_group
    if @event.save
      redirect_to group_path(id: @group), notice: 'Event was successfully created.'
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to group_path(id: @group), notice: 'Event was updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to group_path(params[:group_id]), notice: 'Event was deleted.'
  end

  def register
    if @event.users << current_user
      redirect_to group_event_path(group_id: @group, id: @event),
                  notice: "Yay! You were added to the event #{@event.title}."
    else
      redirect_to group_event_path(group_id: @group, id: @event),
                  alert: "Error occurred. You are already registered for event #{@event.title}!"
    end
  end

  def unregister
    @event.users.delete current_user
    redirect_to group_event_path(group_id: @group, id: @event),
                notice: "You've left event #{@event.title}"
  end

  private

  def load_group
    @group = Group.find(params[:group_id])
  end

  def add_event
    @event = Event.find(params[:id])
  end

  def adjust_group
    @event.group = current_user.administrated_groups.find(params[:group_id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :beginning, :end)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
  <%= form_for([@group, @event], html: {class: 'form-horizontal'}) do |f| %>
      <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
              <% @event.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group row">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-md-5">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :beginning, class: 'col-sm-2 control-label' %>
        <div class="col-md-5">
          <%= f.datetime_select :beginning, {}, {class: 'form-control input-sm datetime-select'} %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :end, class: 'col-sm-2 control-label' %>
        <div class="col-md-5">
          <%= f.datetime_select :end, {}, {class: 'form-control input-sm datetime-select'} %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-md-5">
          <%= f.text_area :description, rows: 6, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-offset-2 col-md-5">
          <%= f.submit class: 'btn btn-default' %>
        </div>
      </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="container">
  <h1>Event <strong><%= @event.title %></strong> of group <strong><%= @event.group.name %></strong></h1>

  <% if @event.group.is_admin? current_user %>
      <p><%= link_to 'Edit event', edit_group_event_path(group_id: @group, id: @event) %></p>
  <% end %>

  <p>
    <% if !@event.is_user_attending? current_user %>
        <%= link_to 'Join this event!', event_register_path(group_id: @group, id: @event), method: :post %>
    <% else %>
        <%= link_to 'Leave this event.', event_unregister_path(group_id: @group, id: @event), method: :post %>
    <% end %>
  </p>

  <h2>From</h2>

  <p><%= @event.beginning.to_s(:long) %></p>

  <h2>To</h2>

  <p><%= @event.end.to_s(:long) %></p>

  <h2>Who is attending?</h2>
  <% if @event.users.any? %>
      <ul>
        <% @event.users.each do |u| %>
            <li><%= link_to u.name, u %></li>
        <% end %>
      </ul>
  <% else %>
      <p>No user has joined yet</p>
  <% end %>

  <p class="well col-md-5">
    <%= @event.description %>
  </p>


</div>