config/routes.rb
Togather::Application.routes.draw do

  #devise_for :users, skip: [:cancel]

  devise_for :users, skip: :registrations
  devise_scope :user do # will disable cancelling the account
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  root to: 'welcome#index'

  get '/user', to: 'users#profile', as: 'profile'
  get '/profile/:id', to: 'users#profile', as: 'user'
  get '/profile', to: 'users#profile', as: 'user_root'

  resources :groups, except: [:index] do
    resources :comments, only: [:create]
    resources :events, except: [:index]
  end
  post '/groups/register/:id', to: 'groups#register', as: 'register'
  post '/groups/unregister/:id', to: 'groups#unregister', as: 'unregister'

  post '/groups/:group_id/events/:id/register', to: 'events#register', as: 'event_register'
  post '/groups/:group_id/events/:id/unregister', to: 'events#unregister', as: 'event_unregister'

  get '/search', to: 'groups#search', as: 'search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Togather</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <span class="navbar-brand"><i class="glyphicon glyphicon-link"></i> <%= link_to 'ToGather', root_path %></span>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
              <li><%= link_to 'My profile', profile_path %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to 'Set up a new group', new_group_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
        <%= form_tag search_path, method: 'get', class: 'navbar-form navbar-right' do %>
            <div class="form-group">
              <%= text_field_tag :q, nil, placeholder: 'Search', class: 'form-control' %>
            </div>
            <%= submit_tag 'Search', name: nil, class: 'btn btn-default' %>
        <% end %>
      </div>

    </div>
  </div>

  <%= yield %>

  <div class="container">
    <hr/>
    <footer><p>Petr Jindracek, 2014</p></footer>
  </div>
</div>

</body>
</html>